function [] = parameters_optimization(n)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/henryliu/Documents/DBoW2-master/demo/debug_log.xls
%    Worksheet: debug_log
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/14 12:15:04

%% Import the data
[~, ~, raw] = xlsread('/Users/henry/Desktop/test_results.xls','debug_log');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
raw = raw(:,[1,2,3,4,5,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
numofimages = data(:,1);
descriptors = data(:,2);
branch = data(:,4);
depth = data(:,5);
accuracy = data(:,6);

%% Clear temporary variables
clearvars data raw cellVectors;

%con = bsxfun(@and,(strcmp(bestmatchedimage(:),' 111207.1.jpg') == true),(numofimages(:) == n));
con = (numofimages(:) == n);
[xq,yq] = meshgrid(5:0.2:20, 3:0.2:12);
vq = griddata(branch(con),depth(con),accuracy(con),xq,yq);
figure
str=sprintf('results for %d images', n);
surf(xq,yq,vq);title(str);xlabel('K');ylabel('L');zlabel('acurracy');
clc;
end
